spring:
  datasource:
    url: jdbc:mysql://localhost:3306/meltingbooks?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: melting
    password: books
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

  jackson:
    serialization:
      INDENT_OUTPUT: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 40738270121-uvsq8v0nt25f0pakjsoooinpd6dqk5d0.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://meltingbooks.o-r.kr:8080/auth/GOOGLE/callback
            scope:
              - email
              - profile
          naver:
            client-id: aEES6oaOIyxTCs9ey0M6
            client-secret: p9eYs1gD54
            redirect-uri: http://meltingbooks.o-r.kr:8080/auth/NAVER/callback
            authorization-grant-type: authorization_code
            scope:
              - email
              - profile
          kakao:
            client-id: 08682e37a5ef2a0e72ac68b22b3c03be
            client-secret: fJ6aO6AS73wnLN5NSXTCkcbIwLKIH3q2
            redirect-uri: http://meltingbooks.o-r.kr:8080/auth/KAKAO/callback
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - account_email
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB

server:
  address: 0.0.0.0
  port: 8080

firebase:
  enabled: false

aladin:
  api:
    key: ttbheebi16541715001
    
badge:
  base-url: "https://objectstorage.ap-osaka-1.oraclecloud.com/n/axfmxzr7cohq/b/melting-images/o"
  
app:
  frontend:
    base-url: https://meltingbooks.o-r.kr

